//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReplicaStock.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.business.soap.bridge.synthesis.com/", ConfigurationName="ServiceReference1.BridgeCoreSOAPService")]
    public interface BridgeCoreSOAPService {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento service del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        ReplicaStock.ServiceReference1.executeResponse execute(ReplicaStock.ServiceReference1.execute request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ReplicaStock.ServiceReference1.executeResponse> executeAsync(ReplicaStock.ServiceReference1.execute request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class execute {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="execute", Namespace="http://services.business.soap.bridge.synthesis.com/", Order=0)]
        public ReplicaStock.ServiceReference1.executeBody Body;
        
        public execute() {
        }
        
        public execute(ReplicaStock.ServiceReference1.executeBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class executeBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string service;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string request;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string store;
        
        public executeBody() {
        }
        
        public executeBody(string service, string request, string store) {
            this.service = service;
            this.request = request;
            this.store = store;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class executeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="executeResponse", Namespace="http://services.business.soap.bridge.synthesis.com/", Order=0)]
        public ReplicaStock.ServiceReference1.executeResponseBody Body;
        
        public executeResponse() {
        }
        
        public executeResponse(ReplicaStock.ServiceReference1.executeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class executeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public executeResponseBody() {
        }
        
        public executeResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BridgeCoreSOAPServiceChannel : ReplicaStock.ServiceReference1.BridgeCoreSOAPService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BridgeCoreSOAPServiceClient : System.ServiceModel.ClientBase<ReplicaStock.ServiceReference1.BridgeCoreSOAPService>, ReplicaStock.ServiceReference1.BridgeCoreSOAPService {
        
        public BridgeCoreSOAPServiceClient() {
        }
        
        public BridgeCoreSOAPServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BridgeCoreSOAPServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BridgeCoreSOAPServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BridgeCoreSOAPServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ReplicaStock.ServiceReference1.executeResponse ReplicaStock.ServiceReference1.BridgeCoreSOAPService.execute(ReplicaStock.ServiceReference1.execute request) {
            return base.Channel.execute(request);
        }
        
        public string execute(string service, string request, string store) {
            ReplicaStock.ServiceReference1.execute inValue = new ReplicaStock.ServiceReference1.execute();
            inValue.Body = new ReplicaStock.ServiceReference1.executeBody();
            inValue.Body.service = service;
            inValue.Body.request = request;
            inValue.Body.store = store;
            ReplicaStock.ServiceReference1.executeResponse retVal = ((ReplicaStock.ServiceReference1.BridgeCoreSOAPService)(this)).execute(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReplicaStock.ServiceReference1.executeResponse> ReplicaStock.ServiceReference1.BridgeCoreSOAPService.executeAsync(ReplicaStock.ServiceReference1.execute request) {
            return base.Channel.executeAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReplicaStock.ServiceReference1.executeResponse> executeAsync(string service, string request, string store) {
            ReplicaStock.ServiceReference1.execute inValue = new ReplicaStock.ServiceReference1.execute();
            inValue.Body = new ReplicaStock.ServiceReference1.executeBody();
            inValue.Body.service = service;
            inValue.Body.request = request;
            inValue.Body.store = store;
            return ((ReplicaStock.ServiceReference1.BridgeCoreSOAPService)(this)).executeAsync(inValue);
        }
    }
}
